//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pimsnotifservice.PimsNotificationService {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PimsSoap11", Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public partial class PimsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NotifySmsDeliveryReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifySmsReceptionOperationCompleted;
        
        /// CodeRemarks
        public PimsService() {
            this.Url = "http://10.17.26.64:7003/wsps/services";
        }
        
        public PimsService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event NotifySmsDeliveryReportCompletedEventHandler NotifySmsDeliveryReportCompleted;
        
        /// CodeRemarks
        public event NotifySmsReceptionCompletedEventHandler NotifySmsReceptionCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("NotifySmsDeliveryReportResponse", Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
        public NotifySmsDeliveryReportResponse NotifySmsDeliveryReport([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")] NotifySmsDeliveryReportRequest NotifySmsDeliveryReportRequest) {
            object[] results = this.Invoke("NotifySmsDeliveryReport", new object[] {
                        NotifySmsDeliveryReportRequest});
            return ((NotifySmsDeliveryReportResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void NotifySmsDeliveryReportAsync(NotifySmsDeliveryReportRequest NotifySmsDeliveryReportRequest) {
            this.NotifySmsDeliveryReportAsync(NotifySmsDeliveryReportRequest, null);
        }
        
        /// CodeRemarks
        public void NotifySmsDeliveryReportAsync(NotifySmsDeliveryReportRequest NotifySmsDeliveryReportRequest, object userState) {
            if ((this.NotifySmsDeliveryReportOperationCompleted == null)) {
                this.NotifySmsDeliveryReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifySmsDeliveryReportOperationCompleted);
            }
            this.InvokeAsync("NotifySmsDeliveryReport", new object[] {
                        NotifySmsDeliveryReportRequest}, this.NotifySmsDeliveryReportOperationCompleted, userState);
        }
        
        private void OnNotifySmsDeliveryReportOperationCompleted(object arg) {
            if ((this.NotifySmsDeliveryReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifySmsDeliveryReportCompleted(this, new NotifySmsDeliveryReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("NotifySmsReceptionResponse", Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
        public NotifySmsReceptionResponse NotifySmsReception([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")] NotifySmsReceptionRequest NotifySmsReceptionRequest) {
            object[] results = this.Invoke("NotifySmsReception", new object[] {
                        NotifySmsReceptionRequest});
            return ((NotifySmsReceptionResponse)(results[0]));
        }
        
        /// CodeRemarks
        public void NotifySmsReceptionAsync(NotifySmsReceptionRequest NotifySmsReceptionRequest) {
            this.NotifySmsReceptionAsync(NotifySmsReceptionRequest, null);
        }
        
        /// CodeRemarks
        public void NotifySmsReceptionAsync(NotifySmsReceptionRequest NotifySmsReceptionRequest, object userState) {
            if ((this.NotifySmsReceptionOperationCompleted == null)) {
                this.NotifySmsReceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifySmsReceptionOperationCompleted);
            }
            this.InvokeAsync("NotifySmsReception", new object[] {
                        NotifySmsReceptionRequest}, this.NotifySmsReceptionOperationCompleted, userState);
        }
        
        private void OnNotifySmsReceptionOperationCompleted(object arg) {
            if ((this.NotifySmsReceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifySmsReceptionCompleted(this, new NotifySmsReceptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public partial class NotifySmsDeliveryReportRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SessionId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageKey;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmsDeliveryInformation DeliveryInformation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NamedParam", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NamedParam[] NamedParam;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public partial class SmsDeliveryInformation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Address Address;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmsDeliveryStatus SmsDeliveryStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SmsDeliveryStatusSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avea.com.tr/pims/schema-common")]
    public partial class Address {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msisdn;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Asid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avea.com.tr/pims/schema-common")]
    public partial class NamedParam {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public enum SmsDeliveryStatus {
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        DeliveryUncertain,
        
        /// <remarks/>
        DeliveryImpossible,
        
        /// <remarks/>
        MessageWaiting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public partial class NotifySmsDeliveryReportResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmsNotificationServiceResultCode resultCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public enum SmsNotificationServiceResultCode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public partial class NotifySmsReceptionRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SessionId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SmsServiceActivationNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Address SenderAddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageKey;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PartTotal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartTotalSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PartNo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartNoSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NamedParam", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NamedParam[] NamedParam;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.avea.com.tr/pims-partner/schema/smsNotification")]
    public partial class NotifySmsReceptionResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmsNotificationServiceResultCode resultCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void NotifySmsDeliveryReportCompletedEventHandler(object sender, NotifySmsDeliveryReportCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifySmsDeliveryReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifySmsDeliveryReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public NotifySmsDeliveryReportResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotifySmsDeliveryReportResponse)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void NotifySmsReceptionCompletedEventHandler(object sender, NotifySmsReceptionCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifySmsReceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifySmsReceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public NotifySmsReceptionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotifySmsReceptionResponse)(this.results[0]));
            }
        }
    }
}
